### ISSUE TITLE
Read-only serializer fields are not applied

### ISSUE THREAD

**Issue by ddobson** [Vacasa/drf-jsonapi#41]
**Describe the bug**

When creating a `ResourceModelSerializer` class, [read_only_fields](https://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields) are not applied to the final representation.

For instance, this code will render JSON without the `created_at` and `modified_at` attributes.

```
class ClusterSerializer(ResourceModelSerializer):
    class Meta:
        type = "cluster"
        base_path = "/clusters"
        model = Cluster
        fields = ["rep_unit"]
        read_only_fields = ["created_at", "modified_at"]
        relationships = {
            "rep_unit": RepUnitRelationshipsHandler(),
            "units": UnitsRelationshipsHandler(),
        }
```

Relevant JSON
```
"data": {
    "type": "cluster",
    "id": 1,
    "attributes": {
      "rep_unit": 1
    },
    "relationships": {
      "rep_unit": {
        "data": {
          "type": "unit",
          "id": 1
        }
      },
      "units": {
        "links": {
          "self": "http://local.units.vacasa.io/clusters/1/relationships/units"
        },
        "data": []
      }
    },
```

**To Reproduce**

1. Add a property of `read_only_fields` to a class that inherits from `ResourceModelSerializer` with some known properties for that model.
1. Make a request to an endpoint that uses that serializer.
1. Observe that those fields are missing from response JSON.

**Expected behavior**

Read-only fields should be represented in the final JSON produced by the serializer and should be writable. Basically, they should work the way they do in DRF.

**Comment by chrisbrantley** [comment]
@ddobson I don't think this is a bug. The issue you describe is the same as DRF.

See: https://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields

In your example if you had changed your field definitions to the following:
```
fields = ["rep_unit", "created_at", "modified_at"]
read_only_fields = ["created_at", "modified_at"]
```
It will work as you expect.

I think the confusion is that `fields` is a list of all the fields for the resource and `read_only_fields` is a list of those fields which should be read_only (will throw an exception if they are set in a request).

**Comment by chrisbrantley** [comment]
I'm going to close this. If I'm wrong feel free to re-open.
