### ISSUE TITLE
Eliminate need to change parameters of get_resource for relationships in app code

### ISSUE THREAD

**Issue by tpansino** [Vacasa/drf-jsonapi#44]
**Is your feature request related to a problem? Please describe.**
When I run `pylint` (via `prospector`) on some code consuming this library, I get a lot of errors along the lines of:
`pylint: arguments-differ / Parameters differ from overridden 'get_resource' method (col 4)`

These errors are caused by many relationship viewset implementations in our application code that look sort of like this:

```python
class UserGroupRelationshipViewSet(
    DebugMixin, ReadOnlyToManyRelationshipViewSet
):
    view_name_prefix = "User Group"
    serializer_class = UserSerializer
    relationship = "groups"

    def get_resource(self, request, user_pk):
        return get_object_or_404(User, pk=user_pk)
```

The issue is that the `def get_resource(self, request, `**`user_pk`**`)` call in this class changes the method signature of the underlying `get_resource` method in the base `ViewSet` class and adds a `user_pk` parameter. We need to somehow not do this to avoid the linter error (and it's probably a violation of SOLID design, not sure which principle).

**Describe the solution you'd like**
Refactor the code to eliminate the need to override this `get_resource` method in consuming application code for relationships so that the `pylint` errors go away. @chrisbrantley has some knowledge of what can be done here and is already working on some code changes that should additionally reduce boilerplate for consuming the library.

**Comment by chrisbrantley** [comment]
@tpansino This is fixed in the new `1.0rc` branch. `pk` is used everywhere and you can override the method keeping the signature consistent. PyLint is happy again.
