### ISSUE TITLE
Update the requirements-dev and example project requirements to secure versions

### ISSUE THREAD

**Issue by ddobson** [Vacasa/drf-jsonapi#52]
There are a number of out-of-date libraries used in the dev-requirements file and the example project requirements file. We should update those to eliminate the warnings.

https://vacasa.pagerduty.com/incidents?assignedToUser=PKU45XP&status=acknowledged%2Ctriggered%2Cresolved

**Comment by jmkuchman** [comment]
This issue is addressed here: https://github.com/Vacasa/drf-jsonapi/pull/67
